name: flutter_contacts_app
description: "A contacts app built with Flutter and SQLite."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.0
  path: ^1.9.0
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  flutter_slidable: ^3.1.1
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
